### ISSUE TITLE
Add support for front matter

### ISSUE THREAD

**Issue by ysegorov** [ysegorov/wt#30]
> The front matter must be the first thing in the file and must take the form of valid YAML set between triple-dashed lines. 

```yaml
---
tags: 
  - python
  - javascript
title: Blogging Like a Hacker
---
```
